const lineasCodigo: string[] = ['',
"buscar(patron, texto){",
"coincidencias = []",
"m = patron.size, n = texto.size",
"alfabeto = 256",
"modulo = 1000000009",
"hashPatron = 0, hashSubString = 0, potenciaMaxima = (alfabeto ^ (m-1)) % modulo;",
"if(patron.size > texto.size){",
"return coincidencias",
"}",
"for(i = 0 hasta m-1){",
"hashPatron = (hashPatron * alfabeto + patron[i]) % modulo",
"hashSubString = (hashSubString * alfabeto + texto[i]) % modulo",
"}",
"",
"for(i = 0 hasta n-m){",
"if(hashPatron == hashSubString){",
"j = 0",
"while(j < m && patron[j] == texto[i+j]){",
"j++;",
"}",
"if(j == m){",
"coincidencias.add(i)",
"}",
"}",
"",
"hashSubString = (hashSubString - texto[i] * potencia) % modulo;",
"hashSubString = (hashSubString * alfabeto) % modulo",
"hashSubString = (hashSubString + texto[i+m]) % modulo",
"if(hashSubString < 0)hashSubString += modulo;",
"}",
"return coincidencias;",
"}"
];

export default lineasCodigo;